config/routes.rb
Rails.application.routes.draw do

  get 'sessions/create'

  get 'sessions/destroy'

  get 'pages/about'

    resources :articles do
        resources :comments
    end
    
    resources :users
    
    get 'admin' => 'admin#index'
    controller :sessions do
        get 'login' => :new
        post 'login' => :create
        delete 'logout' => :destroy
    end

    root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user
    has_many :comments
    validates :title, presence: true, length: {maximum:50}
    validates :post, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :articles
    has_many :comments
  has_secure_password
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    before_action :authorize
    protected
    def authorize
        unless User.find_by(id: session[:user_id])
            redirect_to login_url, notice:"Nie zalogowany"
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
      @article.username = session[:user_name]
      
    respond_to do |format|
      if @article.save
          format.html { redirect_to @article, notice: 'Artykuł został pomyślnie utworzony.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
          format.html { redirect_to @article, notice: 'Artykuł został pomyślnie zedytowany.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Artykuł został usunięty.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
        params.require(:article).permit(:title, :players_lvl, :post)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @article = Article.find(params[:article_id])
       
        @comment = @article.comments.create(comment_params)
         @comment.username = session[:user_name]
        
        respond_to do |format|
        if @comment.save
          format.html { redirect_to article_path(@article), notice: 'Komentarz dodany.' }
            format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
    end
    
    private
    def comment_params
        params.require(:comment).permit(:body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize
  def new
  end

  def create
    user = User.find_by(name: params[:name])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      session[:user_name] = user.name
        redirect_to user, alert: "Użytkownik zalogowany"
    else
        redirect_to login_url, alert: "Niepoprawna kombinacja hasła/użytkownika"
    end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to login_url, alert: "Użytkownik wylogowany"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
    skip_before_action :authorize, only: [:new, :create, :index]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
          format.html { redirect_to users_url, notice: 'Użytkownik pomyślnie utworzony.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
          format.html { redirect_to users_url, notice: 'Użytkownik pomyślnie zmieniony.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
        format.html { redirect_to users_url, notice: 'Użytkownik pomyślnie usunięty.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/articles/_form.html.erb
<%= form_for(article) do |f| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Tytuł' %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label 'Proponowany poziom postaci' %>
    <%= f.number_field :players_lvl %>
  </div>

  <div class="field">
    <%= f.label 'Pomysł na fabułę' %>
    <%= f.text_area :post %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edycja artykułu</h1>

<%= render 'form', article: @article %>

<%= link_to 'Pokaż', @article %> |
<%= link_to 'Powrót', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Artykuły</h1>
</br>
<table>
  <thead>
    <tr>
      <th id='title'>Tytuł</th>
        <th id='lvl'>Proponowany</br> poziom postaci</th>
      <th id='post'>Pomysł na fabułę</th>
     <th><%= link_to 'Nowy artykuł', new_article_path %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <% @articles.reverse_each do |article| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td><%= article.title %></td>
        <td><%= article.players_lvl %></td>
        <td><%= article.post %></td>
        <td><%= link_to 'Pokaż', article %></td>
        <td><%= link_to 'Edytuj', edit_article_path(article) %></td>
          <td><%= link_to 'Usuń', article, method: :delete, data: { confirm: 'Czy aby napewno?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/new.html.erb
<h1>Nowy artykuł</h1>

<%= render 'form', article: @article %>

<%= link_to 'Powrót', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tytuł:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Proponowany poziom postaci:</strong>
  <%= @article.players_lvl %>
</p>

<p>
  <strong>Pomysł na fabułę:</strong>
  <%= @article.post %>
</p>

<p>
  <strong>Pomysł na fabułę:</strong>
    <%= @article.username %>
</p>

<h2>Komentarze:</h2>
<% @article.comments.each do |comment| %>
<p>
    <strong>Użytkownik:</strong>
    <%= comment.username %>
</p>
<p>
    <strong>Komentarz:</strong>
    <%= comment.body %>
</p>
<% end %>

<h2>Skomentuj:</h2>

<%= form_for([@article, @article.comments.build]) do |f| %>
<p>
    <%= f.text_area :body %>
</p>
<p>
    <%= f.submit %>
</p>
<% end %>
    

<%= link_to 'Edytuj', edit_article_path(@article) %> |
<%= link_to 'Powrót', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pomysł na sesję!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="all">
    <nav id="horzNav">
        
        <p> &#9679;&#9679;
        <%= link_to 'Spis', {:controller => 'articles', :action => 'index'} %> &#9679;&#9679;
        <%= link_to 'O autorze', {:controller => 'pages', :action => 'about'} %> &#9679;&#9679;
        <%= link_to 'Uzytkownicy', {:controller => 'users', :action => 'index'} %> &#9679;&#9679;
        <%= link_to 'Wyloguj', {:controller => 'sessions', :action => 'destroy'} %> &#9679;&#9679;
        </p>

    
    </nav>
<div id='all_page'>
    
    <%= yield %>

    </div>
</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>O twórcy</h1>
<div id='o_aut'>
<p>Marcin Szpaderski</br>
Aplikacja zrobiona na potrzeby laboratoriów
</p>
<p><a href="mailto:szpaderskimarcin@gmail.com?Subject=Potrzebna%20pomoc">Skontaktuj się ze mną!</a></p>

</div>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Nazwa' %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label 'Hasło' %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label 'Powtórz hasło' %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edycja użytkownika</h1>

<%= render 'form', user: @user %>

<%= link_to 'Pokaż', @user %> |
<%= link_to 'Powrót', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Użytkownicy</h1></br>

<table>
  <thead>
    <tr>
      <th id="name_u">Nazwa</th>
        <th><%= link_to 'Nowy użytkownik', new_user_path %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td><%= user.name %></td>
        <td><%= link_to 'Pokaż', user %></td>
          <td><%= link_to 'Edytuj', edit_user_path(user) %></td>
        <td><%= link_to 'Usuń', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>Nowy użytkownik</h1>

<%= render 'form', user: @user %>

<%= link_to 'Powrót', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nazwa:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edycja', edit_user_path(@user) %> |
<%= link_to 'Powrót', users_path %>